### ISSUE TITLE
missing plugin 'entity'

### ISSUE THREAD

**Issue by Georgette** [nodezoo/nodezoo-info#39]
There is a require statement for `entity` in `info-dev.js` that can't find an associated module in node_modules. 

I removed the require, and now the system isn't angry at me (seemingly) but the web interface is empty.

So I npm installed `seneca-entity": "0.0.1`, that was removed as a dependency in a prior commit, and added back the require, and all is fine and happy.

So not sure if this is going to be replaced, or we really do need it. I remember seeing a tweet about seneca 2.0 moving entity to a separate package (I think)

**Comment by mcdonnelldean** [comment]
Might be my fault :D
